USE bank_db;

CREATE TABLE clients (
	id INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
	nom VARCHAR(255) NOT NULL,
	prenom VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	
);

CREATE TABLE comptes (
	id INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
	client_id INT NOT NULL,
	solde DECIMAL(10,2) NOT NULL,
	compte_type ENUM("courant","epargne") NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	
)

CREATE TABLE transactions (
	id INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
	transaction_type ENUM("recu","retrait") NOT NULL,
	amount DECIMAL(10,2) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)